### ISSUE TITLE
KeeStand can't export non-Latin characters

### ISSUE THREAD

**Issue by evilrobot69** [evilrobot69/code#25]
keestand.js:293 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range. at HTMLInputElement.<anonymous> (https://keestand.appspot.com/keestand.js:293:47) at HTMLInputElement.handle (https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js:63:330) at HTMLInputElement.o (https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js:56:489)
﻿

**Comment by evilrobot69** [comment]
Fixed: https://github.com/evilrobot69/code/commit/1934fcd0312112bd63c80a05593aead83b1ce52e
